import type {Metadata} from "next";
import "./globals.css";
import fonts from "@/utils/Fonts";

export const metadata: Metadata = {
    title: "00CACTUS",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${fonts.dharma.className} font-bold min-h-screen antialiased overflow-hidden`}>
        {children}
        </body>
        </html>
    );
}
